- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks: 
  - name: print the course info
    ansible.buitin.debug:
      msg: "i am learning {{ course }}, duration is: {{ duration }}, trainer: {{ trainer }}"