- name: gathering facts
  hosts: web
  become: yes
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}" #ansible sets the variable automatically that is ansible_facts