- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}" #ansible_facts is a default variable which we can use to collect the info required

  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat" #os_family == "RedHat" is collected from ansible_facts and as per syntax we have to give as ansible_os_family

  - name: install nginx if Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"