- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt #as this is redirection command command module will not work hence we need to use ansible.builtin.shell