- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0cdb6ea5293f1a031 #from aws server networking subnetID
    sg_id: "sg-001c2affbe1e077cf" #from aws server security security groups
    ami_id: "ami-09c813fb71547fc4f" #from aws server details ami id it will be changing need to note the same
    instances:
    - mysql
    - backend
    - frontend
    zone: dawsconnect.org
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance: #module to create ec2 instance
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}" #as we need to create 3 instances for expense project
# for r53 records we need private and public ip addresses which we will get from above code only i.e. from tasks after creating it will give many values inclusive of ip addresses in return 
    register: ec2_instances #register is the keyword to catch the output

  - name: print the output #printing this to know the output of the servers in order to collect private and public ip addresses
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}" #from this output we need to collect ip addresses for r53 records

#private IP 53
  - name: create r53 private records
    amazon.aws.route53: # module to create r53 records
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.dawsconnect.org
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" #collecting private ip one by one eg: first we get private ip of mysql then backend and last frontend
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.result }}"

  - name: create r53 public record for frontend
    amazon.aws.route53: # module to create r53 records
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #frontend.dawsconnect.org
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.result }}"
    when: item.item == "frontend"